stages:
  - build
  - deploy

build:
  image: gradle:7.5-jdk18
  stage: build
  script:
    - gradle installDist
  artifacts:
    paths:
      - build/
    expire_in: 2 hours
  cache:
    paths:
      - build/

deploy:
  image: docker:stable
  stage: deploy
  #  only:
  #    - master
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker rmi --force 37076284ed4d
    - docker rmi --force 7cd52847ad77
    - docker build -t $CI_REGISTRY/partmanager/api:latest .
    - docker push $CI_REGISTRY/partmanager/api:latest
