ktor:
  application:
    modules:
      - at.eWolveLabs.ApplicationKt.module
  deployment:
    port: 8080
  jwt:
    domain: "https://part01.klaffenboeck.eu/"
    audience: "jwt-audience"
    realm: "ktor sample app"
    secret: "super-secret-key"